<?php
return [
    'transactions'=>array(
        'type'=>array(
            'Withdraw','Deposit'
        ),
        'status'=>array(
          'Pending','Approved','Rejected'
        ),
    ),
    'users'=>array(
        'role'=>array(
            'Client','Admin'
        ),
        'status'=>array(
            'Active','InActive','Blocked'
        )
    )
];
